import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import { CartProvider } from "./context/CartContext";
import { LoadingProvider } from "./context/LoadingContext";
import Loader from "./components/ui/Loader";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
      <CartProvider>
      <LoadingProvider>
        <Header />
        <Loader />
        <main className="min-h-screen">{children}</main>
        <Footer />
        </LoadingProvider>
        </CartProvider>
      </body>
    </html>
  );
}
